name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install and Build pwncat-vl Package
        run: |
          poetry install
          poetry build

      - name: Publish Package to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          publish_method: pypi-oidc

      - name: Download and Archive Plugins
        run: |
          poetry run pwncat-vl --download-plugins
          tar czvf pwncat-plugins.tar.gz --transform='s|.*pwncat/||' ~/.local/share/pwncat/*

      - name: Extract Release Body
        run: |
          version=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "## Changelog" > this_version_changelog.md
          sed -n '/^## \['"$version"'\]/,/^## /p' CHANGELOG.md | head -n -1 | tail -n +2 >> this_version_changelog.md
          echo "[Full Changelog](https://github.com/Chocapikk/pwncat-vl/blob/v$version/CHANGELOG.md)" >> this_version_changelog.md

      - name: Publish Plugins
        uses: softprops/action-gh-release@v1
        with:
          files: "pwncat-plugins.tar.gz"
          body_path: this_version_changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
