name: Python Checks
on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-versions }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install pwncat-vl with pipx
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install .

      - name: Install test dependencies
        run: |
          pip install pycryptodome pytest flake8

      - name: Run tests with pytest
        run: python -m pytest
